### ISSUE TITLE
Make the Background color of line numbers slightly different to the background color of the text

### ISSUE THREAD

**Issue by mogoh** [atom/atom-light-syntax#13]
It is hard to see if a line starts with a space or not because the background is plain white. Please change it (e.g. make the background of the line numbers light grey) so I can see if a line starts with a space or not.

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
