### ISSUE TITLE
.json styling is weird

### ISSUE THREAD

**Issue by maxrahder** [atom/atom-light-syntax#15]
I don't know what plugin does what, but

- object literal properties are styled strangely
- and they are parsed *very* strangely indeed, with *each character* getting wrapped in a &lt;span class="syntax--invalid syntax--illegal syntax--expected-dictionary-separator syntax--json">
 

https://www.dropbox.com/s/zseryuhz7dsta1b/Screenshot%202017-04-26%2009.35.34.jpg?dl=0

Does anyone know what's going on?

**Comment by thomasjo** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
